In [ ]:
"""
-------------------------------------------------------------------------------
Initial visual exploration of selected neighbourhood scenarios to identify
relevant differences, patterns and potential insights for further analysis.

The scenarios are defined by six factors:
- Building type
- Density
- Road layout
- Construction
- Heat supply
- Energy efficiency level

Scenario comparisons:

1. Block vs. Single-family house
   - Block: Block / High density / Curve / Wood / Local energy /  30 kWh
   - Single-family: Single / Low density / Wood / Curve / Local energy / 30 kWh

2. Row house vs. Single-family house
   - Row house: Row / Low density / Grid / Mineral / Local energy / 15 kWh
   - Single-family: Single / Low density / Grid / Mineral / Local energy / 15 kWh 
   - Optimised variant: High density / Wood

3. Dynamic vs. Static QLCA
   - Line house: Line / Medium density / Curve / Mineral / Local energy / 30 kWh 

------------------------------------------------------------------------------
"""

'\n-------------------------------------------------------------------------------\nInitial visual exploration of selected neighbourhood scenarios to identify\nrelevant differences, patterns and potential insights for further analysis.\n\nThe scenarios are defined by six factors:\n- Building type\n- Density\n- Road layout\n- Construction\n- Heat supply\n- Energy demand\n\nScenario comparisons:\n\n1. Block vs. Single-family house\n   - Block: Block / High density / Curve / Wood / Local energy /  30 kWh\n   - Single-family: Single / Low density / Wood / Curve / Local energy / 30 kWh\n\n2. Row house vs. Single-family house\n   - Row house: Row / Low density / Grid / Mineral / Local energy / 15 kWh\n   - Single-family: Single / Low density / Grid / Mineral / Local energy / 15 kWh \n   - Optimised variant: High density / Wood\n\n3. Dynamic vs. Static QLCA\n   - Line house: Line / Medium density / Curve / Mineral / Local energy / 30 kWh \n\n------------------------------------------------------------------------------\n'

In [2]:
"""
------------------------------------------------------------------------------
Libraries
------------------------------------------------------------------------------
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

import plotly.graph_objects as go

In [3]:
# show all columns
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [4]:
"""
------------------------------------------------------------------------------
Import data
------------------------------------------------------------------------------
"""


df = pd.read_csv("../data/csv/QLCA_data.csv")

df.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
0,EH15NGGI,EH15NGGI,EFH,Holz,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,169119,169119.154919,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.0,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887.0,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.031299,False,16650.0,1226.13,1226.13,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,480.03,6.2,450.27,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,136.93,136.93,0.0
1,EH15LGGI,EH15LGGI,EFH,Holz,15 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,117035,117034.638730,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,8862.0,855.0,4757.375085,1772.6688,1476.945552,0.0,25140.0,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,24151.0,24150.548207,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,12.478105,False,16650.0,848.51,848.51,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,64.25,6.2,34.49,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,175.10,175.09,0.0
2,EH15EGGI,EH15EGGI,EFH,Holz,15 kWh,Erdgas,gering,Kreuzung,Gitter,139370,139370.376391,58881.975086,1132.5384,12955.02,5462.376,7694.7384,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12538.68,12057.4,855.0,7952.744057,1772.6688,1476.945552,0.0,25140.0,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,43291.0,43290.916896,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,14.859516,False,16650.0,1010.44,1010.45,426.90,8.21,93.92,39.6,55.79,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,90.91,87.42,6.2,57.66,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,313.86,313.86,0.0
3,EH30NGGI,EH30NGGI,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,177906,177906.089612,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,66670.7,855.0,62566.105633,1772.6688,1476.945552,0.0,25140.0,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,29168.0,29168.013342,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,18.968152,False,16650.0,1289.83,1289.83,412.73,8.21,86.70,39.6,50.61,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,89.14,483.37,6.2,453.61,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,211.47,211.47,0.0
4,EH30LGGI,EH30LGGI,EFH,Holz,30 kWh,LW Wärmepumpe,gering,Kreuzung,Gitter,128443,128443.352089,56927.230286,1132.5384,11958.48,5462.376,6980.7936,1008.0,4590.3,4463.494286,1886.4,2154.48,100.8,4859.748,35.4,12294.42,9079.2,855.0,4974.577506,1772.6688,1476.945552,0.0,25140.0,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,37297.0,37296.803945,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,13.694489,False,16650.0,931.22,931.23,412.73,8.21,86.70,39.6,50.61,7.31,33.28,32.36,13.68,15.62,0.73,35.23,0.26,89.14,65.82,6.2,36.07,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,270.41,270.41,0.0

In [5]:
"""
------------------------------------------------------------------------------
Function: Filter dataset based on the 6 factors
------------------------------------------------------------------------------
"""

def get_scenario(df, scenario):
    mask = pd.Series(True, index=df.index)

    for col, value in scenario.items():
        mask &= df[col] == value

    return df.loc[mask]

In [6]:
"""
------------------------------------------------------------------------------
Scenario1: Block
------------------------------------------------------------------------------
"""

S1_BW = {
    "Typ": "BW",
    "Bauart": "Holz",
    "Energiebedarf": "30 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "hoch",
    "Erschließung (Sied.)": "Schlaufe"
}

In [7]:
df_S1_BW = get_scenario(df, S1_BW)

df_S1_BW.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
849,BH30NHSC,BH30NHSC,BW,Holz,30 kWh,Nahwärme kalt,hoch,Kurve,Schlaufe,1130116,1.130116e+06,343250.914196,4214.209182,30128.76,59328.381369,23427.587988,7752.036923,6415.8,40483.938857,16778.492308,37163.348308,954.304615,91621.044646,4158.72,20824.29,309050.1,83.79,247674.955848,33347.22048,14868.90206,13075.2,183866.0,250.6945,912.0,24.458,10329.393157,4881.38,5626.32,3427.2,0.0,158414.566154,293949.0,293949.088394,0.0,621.0,BW,Schlaufe,60000.0,4728.0,4102.0,2720.0,14769.0,27265.846154,21812.676923,0.24615,1.4769,6.0,88614.0,99520.338462,70891.2,84592.287692,0.267655,7.0,41.0,1729.053659,908.861538,13.359564,True,11550.0,653.6,653.6,198.52,2.44,17.42,34.31,13.55,4.48,3.71,23.41,9.7,21.49,0.55,52.99,2.41,12.04,178.74,0.05,143.24,19.29,8.6,7.56,106.34,0.14,0.53,0.01,5.97,2.82,3.25,1.98,0.0,91.62,170.01,170.01,0.0

In [8]:
row = df_S1_BW.iloc[0]

# Percent
total = row["GWP"]

GWP_S1_BW_pct = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": row["GWP für gesamte Geb.- Erschliessung (KG 500)"] / total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [9]:
kg_colors = {
    "KG300": "#3A86FF", 
    "KG400": "#FD2B3B",
    "KG500": "#10B61D",
    "B6":    "#FFB20B"
}

In [10]:
# Percent

fig = go.Figure()

# KG300
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_BW_pct["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_BW_pct["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# KG500 
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_BW_pct["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_BW_pct["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent – Scenario 1 Block",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [11]:
# HTML
fig.write_html("../charts/html/S1_BW_gwp_chart.html")

In [12]:
df_S1_BW.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
849,BH30NHSC,BH30NHSC,BW,Holz,30 kWh,Nahwärme kalt,hoch,Kurve,Schlaufe,1130116,1.130116e+06,343250.914196,4214.209182,30128.76,59328.381369,23427.587988,7752.036923,6415.8,40483.938857,16778.492308,37163.348308,954.304615,91621.044646,4158.72,20824.29,309050.1,83.79,247674.955848,33347.22048,14868.90206,13075.2,183866.0,250.6945,912.0,24.458,10329.393157,4881.38,5626.32,3427.2,0.0,158414.566154,293949.0,293949.088394,0.0,621.0,BW,Schlaufe,60000.0,4728.0,4102.0,2720.0,14769.0,27265.846154,21812.676923,0.24615,1.4769,6.0,88614.0,99520.338462,70891.2,84592.287692,0.267655,7.0,41.0,1729.053659,908.861538,13.359564,True,11550.0,653.6,653.6,198.52,2.44,17.42,34.31,13.55,4.48,3.71,23.41,9.7,21.49,0.55,52.99,2.41,12.04,178.74,0.05,143.24,19.29,8.6,7.56,106.34,0.14,0.53,0.01,5.97,2.82,3.25,1.98,0.0,91.62,170.01,170.01,0.0

In [13]:
metrics_S1_BW = df_S1_BW[[
    "GWP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF",
    "Person_GWP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "524 Stellplätze",
    "524 Hochgaragen",
    "524 Tiefgaragen"
]]

metrics_S1_BW

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen
849,1130116,343250.914196,309050.1,183866.0,293949.088394,0.0,13.359564,653.6,7.0,41.0,84592.287692,1729.053659,908.861538,11550.0,3427.2,0.0,158414.566154

In [14]:
"""
------------------------------------------------------------------------------
S1: Block without undergreound parking
------------------------------------------------------------------------------
"""

df_S1_BW.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
849,BH30NHSC,BH30NHSC,BW,Holz,30 kWh,Nahwärme kalt,hoch,Kurve,Schlaufe,1130116,1.130116e+06,343250.914196,4214.209182,30128.76,59328.381369,23427.587988,7752.036923,6415.8,40483.938857,16778.492308,37163.348308,954.304615,91621.044646,4158.72,20824.29,309050.1,83.79,247674.955848,33347.22048,14868.90206,13075.2,183866.0,250.6945,912.0,24.458,10329.393157,4881.38,5626.32,3427.2,0.0,158414.566154,293949.0,293949.088394,0.0,621.0,BW,Schlaufe,60000.0,4728.0,4102.0,2720.0,14769.0,27265.846154,21812.676923,0.24615,1.4769,6.0,88614.0,99520.338462,70891.2,84592.287692,0.267655,7.0,41.0,1729.053659,908.861538,13.359564,True,11550.0,653.6,653.6,198.52,2.44,17.42,34.31,13.55,4.48,3.71,23.41,9.7,21.49,0.55,52.99,2.41,12.04,178.74,0.05,143.24,19.29,8.6,7.56,106.34,0.14,0.53,0.01,5.97,2.82,3.25,1.98,0.0,91.62,170.01,170.01,0.0

In [15]:
row = df_S1_BW.iloc[0]

# Percent
total = row["GWP"] - (row["524 Tiefgaragen"] + row["510 Erdaushub Garagen"])

ABS_GWP_S1_BW_pct_no_UP = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": (row["GWP für gesamte Geb.- Erschliessung (KG 500)"]- (row["524 Tiefgaragen"] + row["510 Erdaushub Garagen"])) / total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [16]:
# Percent

fig = go.Figure()

# KG300
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_BW_pct_no_UP["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_BW_pct_no_UP["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# KG500 
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_BW_pct_no_UP["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_BW_pct_no_UP["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent - Scenario 1 Block without underground parrking",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [17]:
# HTML
fig.write_html("../charts/html/S1_BW_gwp_no_UP_chart.html")

In [18]:
df_S1_BW.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
849,BH30NHSC,BH30NHSC,BW,Holz,30 kWh,Nahwärme kalt,hoch,Kurve,Schlaufe,1130116,1.130116e+06,343250.914196,4214.209182,30128.76,59328.381369,23427.587988,7752.036923,6415.8,40483.938857,16778.492308,37163.348308,954.304615,91621.044646,4158.72,20824.29,309050.1,83.79,247674.955848,33347.22048,14868.90206,13075.2,183866.0,250.6945,912.0,24.458,10329.393157,4881.38,5626.32,3427.2,0.0,158414.566154,293949.0,293949.088394,0.0,621.0,BW,Schlaufe,60000.0,4728.0,4102.0,2720.0,14769.0,27265.846154,21812.676923,0.24615,1.4769,6.0,88614.0,99520.338462,70891.2,84592.287692,0.267655,7.0,41.0,1729.053659,908.861538,13.359564,True,11550.0,653.6,653.6,198.52,2.44,17.42,34.31,13.55,4.48,3.71,23.41,9.7,21.49,0.55,52.99,2.41,12.04,178.74,0.05,143.24,19.29,8.6,7.56,106.34,0.14,0.53,0.01,5.97,2.82,3.25,1.98,0.0,91.62,170.01,170.01,0.0

In [19]:
total = row["GWP"] - (row["524 Tiefgaragen"] + row["510 Erdaushub Garagen"])

new_cols = pd.DataFrame({
    "GWP_no_UP": total ,
    "GWP / m² NRF_no_UP": total / df_S1_BW["Nettoraumfläche NRF (m2)"],
    "Person_GWP_no_UP": total / df_S1_BW["Bewohner Kachel insg. (rechnerisch)"],
    "GWP für gesamte Geb.- Erschliessung (KG 500)_no_UP" : df_S1_BW["GWP für gesamte Geb.- Erschliessung (KG 500)"] - (df_S1_BW["524 Tiefgaragen"] + df_S1_BW["510 Erdaushub Garagen"])
})

df_S1_BW = pd.concat([df_S1_BW, new_cols], axis=1)

df_S1_BW.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom),GWP_no_UP,GWP / m² NRF_no_UP,Person_GWP_no_UP,GWP für gesamte Geb.- Erschliessung (KG 500)_no_UP
849,BH30NHSC,BH30NHSC,BW,Holz,30 kWh,Nahwärme kalt,hoch,Kurve,Schlaufe,1130116,1.130116e+06,343250.914196,4214.209182,30128.76,59328.381369,23427.587988,7752.036923,6415.8,40483.938857,16778.492308,37163.348308,954.304615,91621.044646,4158.72,20824.29,309050.1,83.79,247674.955848,33347.22048,14868.90206,13075.2,183866.0,250.6945,912.0,24.458,10329.393157,4881.38,5626.32,3427.2,0.0,158414.566154,293949.0,293949.088394,0.0,621.0,BW,Schlaufe,60000.0,4728.0,4102.0,2720.0,14769.0,27265.846154,21812.676923,0.24615,1.4769,6.0,88614.0,99520.338462,70891.2,84592.287692,0.267655,7.0,41.0,1729.053659,908.861538,13.359564,True,11550.0,653.6,653.6,198.52,2.44,17.42,34.31,13.55,4.48,3.71,23.41,9.7,21.49,0.55,52.99,2.41,12.04,178.74,0.05,143.24,19.29,8.6,7.56,106.34,0.14,0.53,0.01,5.97,2.82,3.25,1.98,0.0,91.62,170.01,170.01,0.0,961372.040689,11.364772,556.01053,15122.040689

In [20]:
metrics_S1_BW_no_UP = df_S1_BW[[
    "GWP_no_UP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)_no_UP",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF_no_UP",
    "Person_GWP_no_UP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "524 Stellplätze"
]].round(2)

metrics_S1_BW_no_UP

,GWP_no_UP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500)_no_UP,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF_no_UP,Person_GWP_no_UP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze
849,961372.04,343250.91,309050.1,15122.04,293949.09,0.0,11.36,556.01,7.0,41.0,84592.29,1729.05,908.86,11550.0,3427.2

In [21]:
"""
------------------------------------------------------------------------------
S1: Single-Family
------------------------------------------------------------------------------
"""

S1_EFH = {
    "Typ": "EFH",
    "Bauart": "Holz",
    "Energiebedarf": "30 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "gering",
    "Erschließung (Sied.)": "Schlaufe"
}

In [22]:
df_S1_EFH = get_scenario(df, S1_EFH)

df_S1_EFH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
111,EH30NGSC,EH30NGSC,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kurve,Schlaufe,149590,149590.267025,49325.927886,981.0696,10359.12,4731.784,6050.528,873.6,3978.26,3866.534286,1634.88,1867.216,87.36,4209.732,30.68,10655.164,57042.7,741.0,53486.715023,1535.5872,1279.444688,0.0,17955.0,416.15,912.0,40.6,30.1392,4881.38,5626.32,3427.2,2620.8,0.0,25267.0,25267.003028,0.0,101.0,EFH,Schlaufe,60000.0,4728.0,4102.0,2720.0,5078.0,NaN,NaN,0.097633,0.13995,1.5,8397.0,10156.0,6093.6,8124.8,0.769396,52.0,51.0,119.482353,52.0,18.411563,False,11550.0,1251.98,1251.99,412.83,8.21,86.7,39.6,50.64,7.31,33.3,32.36,13.68,15.63,0.73,35.23,0.26,89.18,477.42,6.2,447.65,12.85,10.71,0.0,150.27,3.48,7.63,0.34,0.25,40.85,47.09,28.68,21.93,0.0,211.47,211.47,0.0

In [23]:
row = df_S1_EFH.iloc[0]

# Percent
total = row["GWP"]

ABS_GWP_S1_EFH_pct = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": row["GWP für gesamte Geb.- Erschliessung (KG 500)"] / total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [24]:
# Percent
fig = go.Figure()

# KG300
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_EFH_pct["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_EFH_pct["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG500
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_EFH_pct["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S1_EFH_pct["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent – Scenario 1 Single-Family",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [25]:
# HTML
fig.write_html("../charts/html/S1_EFH_gwp_chart.html")

In [26]:
df_S1_EFH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
111,EH30NGSC,EH30NGSC,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kurve,Schlaufe,149590,149590.267025,49325.927886,981.0696,10359.12,4731.784,6050.528,873.6,3978.26,3866.534286,1634.88,1867.216,87.36,4209.732,30.68,10655.164,57042.7,741.0,53486.715023,1535.5872,1279.444688,0.0,17955.0,416.15,912.0,40.6,30.1392,4881.38,5626.32,3427.2,2620.8,0.0,25267.0,25267.003028,0.0,101.0,EFH,Schlaufe,60000.0,4728.0,4102.0,2720.0,5078.0,NaN,NaN,0.097633,0.13995,1.5,8397.0,10156.0,6093.6,8124.8,0.769396,52.0,51.0,119.482353,52.0,18.411563,False,11550.0,1251.98,1251.99,412.83,8.21,86.7,39.6,50.64,7.31,33.3,32.36,13.68,15.63,0.73,35.23,0.26,89.18,477.42,6.2,447.65,12.85,10.71,0.0,150.27,3.48,7.63,0.34,0.25,40.85,47.09,28.68,21.93,0.0,211.47,211.47,0.0

In [27]:
metrics_S1_EFH = df_S1_EFH[[
    "GWP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF",
    "Person_GWP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "524 Stellplätze",
    "524 Hochgaragen",
    "524 Tiefgaragen"
]].round(2)

metrics_S1_EFH

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen
111,149590,49325.93,57042.7,17955.0,25267.0,0.0,18.41,1251.98,52.0,51.0,8124.8,119.48,52.0,11550.0,3427.2,2620.8,0.0

In [28]:
"""
------------------------------------------------------------------------------
S1: Single-Family without above ground parking
------------------------------------------------------------------------------
"""

df_S1_EFH = get_scenario(df, S1_EFH)

df_S1_EFH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
111,EH30NGSC,EH30NGSC,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kurve,Schlaufe,149590,149590.267025,49325.927886,981.0696,10359.12,4731.784,6050.528,873.6,3978.26,3866.534286,1634.88,1867.216,87.36,4209.732,30.68,10655.164,57042.7,741.0,53486.715023,1535.5872,1279.444688,0.0,17955.0,416.15,912.0,40.6,30.1392,4881.38,5626.32,3427.2,2620.8,0.0,25267.0,25267.003028,0.0,101.0,EFH,Schlaufe,60000.0,4728.0,4102.0,2720.0,5078.0,NaN,NaN,0.097633,0.13995,1.5,8397.0,10156.0,6093.6,8124.8,0.769396,52.0,51.0,119.482353,52.0,18.411563,False,11550.0,1251.98,1251.99,412.83,8.21,86.7,39.6,50.64,7.31,33.3,32.36,13.68,15.63,0.73,35.23,0.26,89.18,477.42,6.2,447.65,12.85,10.71,0.0,150.27,3.48,7.63,0.34,0.25,40.85,47.09,28.68,21.93,0.0,211.47,211.47,0.0

In [29]:
# EFH without parking
row = df_S1_EFH.iloc[0]

# Percent
total = row["GWP"] - (row["524 Hochgaragen"] + row["510 Erdaushub Leitungen"])

GWP_S1_EFH_pct_no_AP = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": (row["GWP für gesamte Geb.- Erschliessung (KG 500)"] - (row["524 Hochgaragen"]+ row["510 Erdaushub Leitungen"]))/ total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [30]:
# Percent

fig = go.Figure()

# KG300
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_EFH_pct_no_AP["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_EFH_pct_no_AP["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG500
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_EFH_pct_no_AP["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[GWP_S1_EFH_pct_no_AP["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent - Scenario 1 Single-Family without above-ground parking",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [31]:
# HTML
fig.write_html("../charts/html/S1_EFH_gwp_no_AP_chart.html")

In [32]:
df_S1_EFH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
111,EH30NGSC,EH30NGSC,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kurve,Schlaufe,149590,149590.267025,49325.927886,981.0696,10359.12,4731.784,6050.528,873.6,3978.26,3866.534286,1634.88,1867.216,87.36,4209.732,30.68,10655.164,57042.7,741.0,53486.715023,1535.5872,1279.444688,0.0,17955.0,416.15,912.0,40.6,30.1392,4881.38,5626.32,3427.2,2620.8,0.0,25267.0,25267.003028,0.0,101.0,EFH,Schlaufe,60000.0,4728.0,4102.0,2720.0,5078.0,NaN,NaN,0.097633,0.13995,1.5,8397.0,10156.0,6093.6,8124.8,0.769396,52.0,51.0,119.482353,52.0,18.411563,False,11550.0,1251.98,1251.99,412.83,8.21,86.7,39.6,50.64,7.31,33.3,32.36,13.68,15.63,0.73,35.23,0.26,89.18,477.42,6.2,447.65,12.85,10.71,0.0,150.27,3.48,7.63,0.34,0.25,40.85,47.09,28.68,21.93,0.0,211.47,211.47,0.0

In [33]:
total = row["GWP"] - (row["524 Hochgaragen"] + row["524 Tiefgaragen"])

new_cols = pd.DataFrame({
    "GWP_no_AP": total ,
    "GWP / m² NRF_no_AP": total / df_S1_EFH["Nettoraumfläche NRF (m2)"],
    "Person_GWP_no_AP": total / df_S1_EFH["Bewohner Kachel insg. (rechnerisch)"],
    "GWP für gesamte Geb.- Erschliessung (KG 500)_no_AP" : df_S1_EFH["GWP für gesamte Geb.- Erschliessung (KG 500)"] - (df_S1_EFH["524 Hochgaragen"] + df_S1_EFH["510 Erdaushub Garagen"])
})

df_S1_EFH = pd.concat([df_S1_EFH, new_cols], axis=1)

df_S1_EFH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom),GWP_no_AP,GWP / m² NRF_no_AP,Person_GWP_no_AP,GWP für gesamte Geb.- Erschliessung (KG 500)_no_AP
111,EH30NGSC,EH30NGSC,EFH,Holz,30 kWh,Nahwärme kalt,gering,Kurve,Schlaufe,149590,149590.267025,49325.927886,981.0696,10359.12,4731.784,6050.528,873.6,3978.26,3866.534286,1634.88,1867.216,87.36,4209.732,30.68,10655.164,57042.7,741.0,53486.715023,1535.5872,1279.444688,0.0,17955.0,416.15,912.0,40.6,30.1392,4881.38,5626.32,3427.2,2620.8,0.0,25267.0,25267.003028,0.0,101.0,EFH,Schlaufe,60000.0,4728.0,4102.0,2720.0,5078.0,NaN,NaN,0.097633,0.13995,1.5,8397.0,10156.0,6093.6,8124.8,0.769396,52.0,51.0,119.482353,52.0,18.411563,False,11550.0,1251.98,1251.99,412.83,8.21,86.7,39.6,50.64,7.31,33.3,32.36,13.68,15.63,0.73,35.23,0.26,89.18,477.42,6.2,447.65,12.85,10.71,0.0,150.27,3.48,7.63,0.34,0.25,40.85,47.09,28.68,21.93,0.0,211.47,211.47,0.0,146969.2,18.088962,1230.049429,15304.0608

In [34]:
metrics_S1_EFH_no_AP = df_S1_EFH[[
    "GWP_no_AP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)_no_AP",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF_no_AP",
    "Person_GWP_no_AP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "524 Stellplätze",
]].round(2)

metrics_S1_EFH_no_AP

,GWP_no_AP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500)_no_AP,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF_no_AP,Person_GWP_no_AP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze
111,146969.2,49325.93,57042.7,15304.06,25267.0,0.0,18.09,1230.05,52.0,51.0,8124.8,119.48,52.0,11550.0,3427.2

In [35]:
"""
------------------------------------------------------------------------------
S1: Overview metrics
------------------------------------------------------------------------------
"""
print("Block:\n")
metrics_S1_BW

Block:

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen
849,1130116,343250.914196,309050.1,183866.0,293949.088394,0.0,13.359564,653.6,7.0,41.0,84592.287692,1729.053659,908.861538,11550.0,3427.2,0.0,158414.566154

In [36]:
print("Block without underground parking:\n")
metrics_S1_BW_no_UP

Block without underground parking:

,GWP_no_UP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500)_no_UP,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF_no_UP,Person_GWP_no_UP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze
849,961372.04,343250.91,309050.1,15122.04,293949.09,0.0,11.36,556.01,7.0,41.0,84592.29,1729.05,908.86,11550.0,3427.2

In [37]:
print("Single-Family detached house:")
metrics_S1_EFH

Single-Family detached house:

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen
111,149590,49325.93,57042.7,17955.0,25267.0,0.0,18.41,1251.98,52.0,51.0,8124.8,119.48,52.0,11550.0,3427.2,2620.8,0.0

In [38]:
print("Single-Family detached house without above-ground parking:")
metrics_S1_EFH_no_AP

Single-Family detached house without above-ground parking:

,GWP_no_AP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500)_no_AP,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF_no_AP,Person_GWP_no_AP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,524 Stellplätze
111,146969.2,49325.93,57042.7,15304.06,25267.0,0.0,18.09,1230.05,52.0,51.0,8124.8,119.48,52.0,11550.0,3427.2

In [39]:
"""
------------------------------------------------------------------------------
S2: Row House
------------------------------------------------------------------------------
"""

S2_RH = {
    "Typ": "RH",
    "Bauart": "Massiv",
    "Energiebedarf": "15 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "gering",
    "Erschließung (Sied.)": "Gitter"
}

In [40]:
df_S2_RH = get_scenario(df, S2_RH)

df_S2_RH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
45,RM15NGGI,RM15NGGI,RH,Massiv,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,314210,314210.33634,119342.826686,2422.728,27713.4,11831.04,15817.185,1134.0,5268.12,9548.314286,3428.37,5262.1074,145.53,11666.04,21.24,25084.752,127135.8,1580.04,118513.506076,3918.4992,3123.76284,0.0,27329.0,742.182,1368.0,72.408,57.3804,6647.34,8310.96,5140.8,4989.6,0.0,40403.0,40403.031138,0.0,300.0,RH,Gitter,60000.0,6984.0,5586.0,4080.0,12540.0,NaN,NaN,0.23375,0.33825,1.5,20295.0,25080.0,15048.0,20064.0,0.568715,36.0,47.0,320.170213,99.0,15.660404,False,16650.0,981.38,981.39,372.75,7.57,86.56,36.95,49.4,3.54,16.45,29.82,10.71,16.44,0.45,36.44,0.07,78.35,397.09,4.93,370.16,12.24,9.76,0.0,85.36,2.32,4.27,0.23,0.18,20.76,25.96,16.06,15.58,0.0,126.19,126.19,0.0

In [41]:
row = df_S2_RH.iloc[0]

total = row["GWP"]

ABS_GWP_S2_RH_pct = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": row["GWP für gesamte Geb.- Erschliessung (KG 500)"] / total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [42]:
fig = go.Figure()


# KG300
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_RH_pct["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_RH_pct["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG500
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_RH_pct["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_RH_pct["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent – Scenario 2 Row house",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [43]:
# HTML
fig.write_html("../charts/html/S2_RH_gwp_chart.html")

In [44]:
df_S2_RH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
45,RM15NGGI,RM15NGGI,RH,Massiv,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,314210,314210.33634,119342.826686,2422.728,27713.4,11831.04,15817.185,1134.0,5268.12,9548.314286,3428.37,5262.1074,145.53,11666.04,21.24,25084.752,127135.8,1580.04,118513.506076,3918.4992,3123.76284,0.0,27329.0,742.182,1368.0,72.408,57.3804,6647.34,8310.96,5140.8,4989.6,0.0,40403.0,40403.031138,0.0,300.0,RH,Gitter,60000.0,6984.0,5586.0,4080.0,12540.0,NaN,NaN,0.23375,0.33825,1.5,20295.0,25080.0,15048.0,20064.0,0.568715,36.0,47.0,320.170213,99.0,15.660404,False,16650.0,981.38,981.39,372.75,7.57,86.56,36.95,49.4,3.54,16.45,29.82,10.71,16.44,0.45,36.44,0.07,78.35,397.09,4.93,370.16,12.24,9.76,0.0,85.36,2.32,4.27,0.23,0.18,20.76,25.96,16.06,15.58,0.0,126.19,126.19,0.0

In [45]:
metrics_S2_RH = df_S2_RH[[
    "GWP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF",
    "Person_GWP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "322 Bodenplatte",
    "351 Decken",
    "361 Dach",
    "A/V-Verhältnis Wohngebäude"
]].round(2)

metrics_S2_RH

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,322 Bodenplatte,351 Decken,361 Dach,A/V-Verhältnis Wohngebäude
45,314210,119342.83,127135.8,27329.0,40403.03,0.0,15.66,981.38,36.0,47.0,20064.0,320.17,99.0,16650.0,27713.4,11666.04,25084.75,0.57

In [46]:
"""
------------------------------------------------------------------------------
S2: Single-Family
------------------------------------------------------------------------------
"""

S2_EFH = {
    "Typ": "EFH",
    "Bauart": "Massiv",
    "Energiebedarf": "15 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "gering",
    "Erschließung (Sied.)": "Gitter"
}

In [47]:
df_S2_EFH = get_scenario(df, S2_EFH)

df_S2_EFH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
9,EM15NGGI,EM15NGGI,EFH,Massiv,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,179932,179932.100519,69694.920686,1132.5384,12955.02,5462.376,16262.076,1008.0,4590.3,4463.494286,2966.4,2842.08,100.8,5337.756,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.0,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887.0,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,19.184163,False,16650.0,1304.52,1304.52,505.29,8.21,93.92,39.6,117.9,7.31,33.28,32.36,21.51,20.61,0.73,38.7,0.26,90.91,480.03,6.2,450.27,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,136.93,136.93,0.0

In [48]:
row = df_S2_EFH.iloc[0]

total = row["GWP"]

ABS_GWP_S2_EFH_pct = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": row["GWP für gesamte Geb.- Erschliessung (KG 500)"] / total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [49]:
fig = go.Figure()


# KG300
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_pct["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_pct["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG500
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_pct["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_pct["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent – Scenario 2 Single-Family",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [50]:
# HTML
fig.write_html("../charts/html/S2_EFH_gwp_chart.html")

In [51]:
df_S2_EFH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
9,EM15NGGI,EM15NGGI,EFH,Massiv,15 kWh,Nahwärme kalt,gering,Kreuzung,Gitter,179932,179932.100519,69694.920686,1132.5384,12955.02,5462.376,16262.076,1008.0,4590.3,4463.494286,2966.4,2842.08,100.8,5337.756,35.4,12538.68,66210.1,855.0,62105.472294,1772.6688,1476.945552,0.0,25140.0,559.65,1368.0,54.6,34.776,6647.34,8310.96,5140.8,3024.0,0.0,18887.0,18886.967188,0.0,100.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,5862.0,NaN,NaN,0.1127,0.16155,1.5,9693.0,11724.0,7034.4,9379.2,0.769486,60.0,51.0,137.929412,60.0,19.184163,False,16650.0,1304.52,1304.52,505.29,8.21,93.92,39.6,117.9,7.31,33.28,32.36,21.51,20.61,0.73,38.7,0.26,90.91,480.03,6.2,450.27,12.85,10.71,0.0,182.27,4.06,9.92,0.4,0.25,48.19,60.26,37.27,21.92,0.0,136.93,136.93,0.0

In [52]:
metrics_S2_EFH = df_S2_EFH[[
    "GWP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF",
    "Person_GWP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "322 Bodenplatte",
    "351 Decken",
    "361 Dach",
    "A/V-Verhältnis Wohngebäude"
]].round(2)

metrics_S2_EFH

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,322 Bodenplatte,351 Decken,361 Dach,A/V-Verhältnis Wohngebäude
9,179932,69694.92,66210.1,25140.0,18886.97,0.0,19.18,1304.52,60.0,51.0,9379.2,137.93,60.0,16650.0,12955.02,5337.76,12538.68,0.77

In [53]:
"""
------------------------------------------------------------------------------
S2: Single-Family high density + wood
------------------------------------------------------------------------------
"""

S2_EFH_opt = {
    "Typ": "EFH",
    "Bauart": "Holz",
    "Energiebedarf": "15 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "hoch",
    "Erschließung (Sied.)": "Gitter"
}

In [54]:
df_S2_EFH_opt = get_scenario(df, S2_EFH_opt)

df_S2_EFH_opt.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
648,EH15NHGI,EH15NHGI,EFH,Holz,15 kWh,Nahwärme kalt,hoch,Kreuzung,Gitter,258391,258391.324267,101573.18112,1584.74232,18127.746,12694.668,15936.324,1411.2,5753.4048,10409.49,2751.84,3016.272,141.12,14600.838,99.12,15046.416,86313.0,1197.0,77605.481952,4134.1104,3376.377816,0.0,26458.0,645.75,1368.0,63.0,48.6864,6647.34,8310.96,5140.8,4233.6,0.0,44047.0,44047.036578,0.0,120.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,8202.6,NaN,NaN,0.15771,0.362775,2.5,21766.5,24607.8,16405.2,19686.24,0.656848,84.0,51.0,321.670588,84.0,13.125479,False,16650.0,803.28,803.28,315.77,4.93,56.35,39.46,49.54,4.39,17.89,32.36,8.55,9.38,0.44,45.39,0.31,46.78,268.33,3.72,241.26,12.85,10.5,0.0,82.25,2.01,4.25,0.2,0.15,20.67,25.84,15.98,13.16,0.0,136.93,136.93,0.0

In [55]:
row = df_S2_EFH_opt.iloc[0]

total = row["GWP"]

ABS_GWP_S2_EFH_opt_pct = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": row["GWP für gesamte Geb.- Erschliessung (KG 500)"] / total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [56]:
fig = go.Figure()

# KG300
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_opt_pct["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_opt_pct["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG500
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_opt_pct["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S2_EFH_opt_pct["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent – Scenario 2 Single-Family high density + wood",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [57]:
# HTML
fig.write_html("../charts/html/S2_EFH_opt_gwp_chart.html")

In [58]:
df_S2_EFH_opt.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
648,EH15NHGI,EH15NHGI,EFH,Holz,15 kWh,Nahwärme kalt,hoch,Kreuzung,Gitter,258391,258391.324267,101573.18112,1584.74232,18127.746,12694.668,15936.324,1411.2,5753.4048,10409.49,2751.84,3016.272,141.12,14600.838,99.12,15046.416,86313.0,1197.0,77605.481952,4134.1104,3376.377816,0.0,26458.0,645.75,1368.0,63.0,48.6864,6647.34,8310.96,5140.8,4233.6,0.0,44047.0,44047.036578,0.0,120.0,EFH,Gitter,60000.0,6984.0,5586.0,4080.0,8202.6,NaN,NaN,0.15771,0.362775,2.5,21766.5,24607.8,16405.2,19686.24,0.656848,84.0,51.0,321.670588,84.0,13.125479,False,16650.0,803.28,803.28,315.77,4.93,56.35,39.46,49.54,4.39,17.89,32.36,8.55,9.38,0.44,45.39,0.31,46.78,268.33,3.72,241.26,12.85,10.5,0.0,82.25,2.01,4.25,0.2,0.15,20.67,25.84,15.98,13.16,0.0,136.93,136.93,0.0

In [59]:
metrics_S2_EFH_opt = df_S2_EFH_opt[[
    "GWP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF",
    "Person_GWP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "322 Bodenplatte",
    "351 Decken",
    "361 Dach",
    "A/V-Verhältnis Wohngebäude"
]].round(2)

metrics_S2_EFH_opt

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,322 Bodenplatte,351 Decken,361 Dach,A/V-Verhältnis Wohngebäude
648,258391,101573.18,86313.0,26458.0,44047.04,0.0,13.13,803.28,84.0,51.0,19686.24,321.67,84.0,16650.0,18127.75,14600.84,15046.42,0.66

In [60]:
"""
------------------------------------------------------------------------------
S2: Single-Family high density + wood
------------------------------------------------------------------------------
"""

S2_EFH_opt = {
    "Typ": "RH",
    "Bauart": "Holz",
    "Energiebedarf": "15 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "hoch",
    "Erschließung (Sied.)": "Gitter"
}

In [61]:
"""
------------------------------------------------------------------------------
S2: Overview metrics
------------------------------------------------------------------------------
"""

print("Row House:\n")
metrics_S2_RH

Row House:

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,322 Bodenplatte,351 Decken,361 Dach,A/V-Verhältnis Wohngebäude
45,314210,119342.83,127135.8,27329.0,40403.03,0.0,15.66,981.38,36.0,47.0,20064.0,320.17,99.0,16650.0,27713.4,11666.04,25084.75,0.57

In [62]:
print("Single-Family:\n")
metrics_S2_EFH

Single-Family:

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,322 Bodenplatte,351 Decken,361 Dach,A/V-Verhältnis Wohngebäude
9,179932,69694.92,66210.1,25140.0,18886.97,0.0,19.18,1304.52,60.0,51.0,9379.2,137.93,60.0,16650.0,12955.02,5337.76,12538.68,0.77

In [63]:
print("Single-Family high density + wood:\n")
metrics_S2_EFH_opt

Single-Family high density + wood:

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,322 Bodenplatte,351 Decken,361 Dach,A/V-Verhältnis Wohngebäude
648,258391,101573.18,86313.0,26458.0,44047.04,0.0,13.13,803.28,84.0,51.0,19686.24,321.67,84.0,16650.0,18127.75,14600.84,15046.42,0.66

In [64]:
"""
------------------------------------------------------------------------------
S3: Most common urban development
Zeilenhaus
(Zeile), Mittlere Dichte, Schlaufe, 30 kWh, Massivbau, Nahwärme  
------------------------------------------------------------------------------
"""

S3_ZH = {
    "Typ": "ZH",
    "Bauart": "Massiv",
    "Energiebedarf": "30 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "mittel",
    "Erschließung (Sied.)": "Schlaufe"
}

In [65]:
df_S3_ZH = get_scenario(df, S3_ZH)

df_S3_ZH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
498,ZM30NMSC,ZM30NMSC,ZH,Massiv,30 kWh,Nahwärme kalt,mittel,Kurve,Schlaufe,800498,800497.734249,291533.042761,2455.078597,26328.24,34764.808062,45678.672837,4716.406154,13018.45,23584.793143,36104.2656,17398.611692,889.521231,58968.155446,1039.68,26586.36,224245.9,246.24,192641.537354,19427.14368,8662.200103,3268.8,113472.0,291.592,912.0,28.448,6017.611126,4881.38,5626.32,3427.2,0.0,92287.827692,171246.0,171246.391532,0.0,511.0,Zeile,Schlaufe,60000.0,4728.0,4102.0,2720.0,12906.0,15884.307692,12707.446154,0.2151,0.8604,4.0,51624.0,57977.723077,41299.2,49281.064615,0.348417,16.0,41.0,1007.297561,529.476923,16.243515,True,11550.0,794.7,794.7,289.42,2.44,26.14,34.51,45.35,4.68,12.92,23.41,35.84,17.27,0.88,58.54,1.03,26.39,222.62,0.24,191.25,19.29,8.6,3.25,112.65,0.29,0.91,0.03,5.97,4.85,5.59,3.4,0.0,91.62,170.01,170.01,0.0

In [66]:
row = df_S3_ZH.iloc[0]

total = row["GWP"]

ABS_GWP_S3_ZH_pct = {
    "KG300": row["GWP für Bauwerk (KG 300)"] / total,
    "KG400": row["GWP für Haustechnik (KG 400)"] / total,
    "KG500": row["GWP für gesamte Geb.- Erschliessung (KG 500)"] / total,
    "B6": row["GWP für Wärmeversorgung (B6)"] / total
}

In [67]:
fig = go.Figure()

# KG300 
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_pct["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_pct["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG500
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_pct["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_pct["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent – Scenario 3 Line",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [68]:
# HTML
fig.write_html("../charts/html/S3_ZH_gwp_chart.html")

In [69]:
df_S3_ZH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
498,ZM30NMSC,ZM30NMSC,ZH,Massiv,30 kWh,Nahwärme kalt,mittel,Kurve,Schlaufe,800498,800497.734249,291533.042761,2455.078597,26328.24,34764.808062,45678.672837,4716.406154,13018.45,23584.793143,36104.2656,17398.611692,889.521231,58968.155446,1039.68,26586.36,224245.9,246.24,192641.537354,19427.14368,8662.200103,3268.8,113472.0,291.592,912.0,28.448,6017.611126,4881.38,5626.32,3427.2,0.0,92287.827692,171246.0,171246.391532,0.0,511.0,Zeile,Schlaufe,60000.0,4728.0,4102.0,2720.0,12906.0,15884.307692,12707.446154,0.2151,0.8604,4.0,51624.0,57977.723077,41299.2,49281.064615,0.348417,16.0,41.0,1007.297561,529.476923,16.243515,True,11550.0,794.7,794.7,289.42,2.44,26.14,34.51,45.35,4.68,12.92,23.41,35.84,17.27,0.88,58.54,1.03,26.39,222.62,0.24,191.25,19.29,8.6,3.25,112.65,0.29,0.91,0.03,5.97,4.85,5.59,3.4,0.0,91.62,170.01,170.01,0.0

In [70]:
metrics_S3_ZH = df_S3_ZH[[
    "GWP",
    "GWP für Bauwerk (KG 300)",
    "GWP für Haustechnik (KG 400)",
    "GWP für gesamte Geb.- Erschliessung (KG 500)",
    "GWP für Wärmeversorgung (B6)",
    "GWP für Nutzstrom",
    "GWP / m² NRF",
    "Person_GWP",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²",
    "Person_GWP (Summe Betrieb & Nutzstrom)",
    "Person_GWP (GWP für Nutzstrom)"
]].round(2)

metrics_S3_ZH

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (GWP für Nutzstrom)
498,800498,291533.04,224245.9,113472.0,171246.39,0.0,16.24,794.7,16.0,41.0,49281.06,1007.3,529.48,11550.0,170.01,0.0

In [71]:
"""
------------------------------------------------------------------------------
S3: Most common urban development
Zeilenhaus
(Zeile), Mittlere Dichte, Schlaufe, 30 kWh, Massivbau, Nahwärme  
dynamic LCA
B6 degression 12% per year
KG300 degression 5% per year
------------------------------------------------------------------------------
"""

S3_ZH_50 = {
    "Typ": "ZH",
    "Bauart": "Massiv",
    "Energiebedarf": "30 kWh",
    "Versorgungsart": "Nahwärme kalt",
    "Dichte": "mittel",
    "Erschließung (Sied.)": "Schlaufe"
}

In [72]:
# static scenario
df_S3_ZH = get_scenario(df, S3_ZH)

df_S3_ZH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
498,ZM30NMSC,ZM30NMSC,ZH,Massiv,30 kWh,Nahwärme kalt,mittel,Kurve,Schlaufe,800498,800497.734249,291533.042761,2455.078597,26328.24,34764.808062,45678.672837,4716.406154,13018.45,23584.793143,36104.2656,17398.611692,889.521231,58968.155446,1039.68,26586.36,224245.9,246.24,192641.537354,19427.14368,8662.200103,3268.8,113472.0,291.592,912.0,28.448,6017.611126,4881.38,5626.32,3427.2,0.0,92287.827692,171246.0,171246.391532,0.0,511.0,Zeile,Schlaufe,60000.0,4728.0,4102.0,2720.0,12906.0,15884.307692,12707.446154,0.2151,0.8604,4.0,51624.0,57977.723077,41299.2,49281.064615,0.348417,16.0,41.0,1007.297561,529.476923,16.243515,True,11550.0,794.7,794.7,289.42,2.44,26.14,34.51,45.35,4.68,12.92,23.41,35.84,17.27,0.88,58.54,1.03,26.39,222.62,0.24,191.25,19.29,8.6,3.25,112.65,0.29,0.91,0.03,5.97,4.85,5.59,3.4,0.0,91.62,170.01,170.01,0.0

In [73]:
kg300 = 186420.39
kg400 = 156378.66
kg500 = 113346.44
b6 = 28435.17
total = kg300 + kg400 + kg500 + b6

ABS_GWP_S3_ZH_50_pct = {
    "KG300": kg300 / total,
    "KG400": kg400 / total,
    "KG500": kg500 / total,
    "B6": b6 / total
}

In [74]:
fig = go.Figure()

# KG300 
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_50_pct["KG300"]],
    name="KG300",
    marker_color=kg_colors["KG300"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG400
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_50_pct["KG400"]],
    name="KG400",
    marker_color=kg_colors["KG400"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

# KG500
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_50_pct["KG500"]],
    name="KG500",
    marker_color=kg_colors["KG500"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))


# B6
fig.add_trace(go.Bar(
    x=["Scenario"],
    y=[ABS_GWP_S3_ZH_50_pct["B6"]],
    name="B6",
    marker_color=kg_colors["B6"],
    width=0.3,
    marker_line_color="white",
    marker_line_width=1
))

fig.update_layout(
    barmode="stack",
    title="GWP Breakdown in percent – Scenario 3 Line, Decarbonisation +50 years",
    yaxis_title="Share of total GWP",
    legend_title="Components",
    height=1000,
    width=1100,
    legend=dict(orientation="h", y=-0.2),
    legend_traceorder="normal",
    yaxis=dict(
        tickformat=".0%",
        range=[0, 1]
    )
)

fig.show()

In [75]:
# HTML
fig.write_html("../charts/html/S3_ZH_50_gwp_chart.html")

In [76]:
df_S3_ZH.head()

,Siedlungs-Code,Flächen-Code,Typ,Bauart,Energiebedarf,Versorgungsart,Dichte,Erschließung (Segm.),Erschließung (Sied.),GWP,GWP ohne Strom,GWP für Bauwerk (KG 300),310 Erdaushub Keller,322 Bodenplatte,325 Bodenbelag,331 Außenwand,334 Außentüren,339 Kellerwände,334 Fenster,341 Innenwände tragend (inkl. Aufzugschacht),342 Innenwände,344 Innentüren,351 Decken,351 Treppe,361 Dach,GWP für Haustechnik (KG 400),"410 Abwasser, Trinkwasser",420 Wärmeversorgung,430 Lüftung,440 Strom,460 Aufzug,GWP für gesamte Geb.- Erschliessung (KG 500),500 Quartiersstrom,500 Quartierswasserleitung,510 Erdaushub Leitungen,510 Erdaushub Garagen,521 Gehweg Radweg,522 Straße,524 Stellplätze,524 Hochgaragen,524 Tiefgaragen,Summe Betrieb & Nutzstrom,GWP für Wärmeversorgung (B6),GWP für Nutzstrom,Nr.,Gebäudetyp,Straßenform/ Erschließungstyp,Gesamtfläche,Straßenflächen (öffentlich),Rad- und Gehwegflächen (öffentlich),Oberirdische Stellplatzflächen (öffentlich),Grundflächen Wohngebäude (brutto),Flächen Tiefgaragen (brutto) (2),Flächen Tiefgaragen (netto) (3),Quartiers-GRZ,Quartiers-GFZ,Obergeschosse,BGF (m²) inkl. oberirdische Garagen,BGF (m²) Wohnen (inkl. Keller),Nettowohnfläche NUF (m2),Nettoraumfläche NRF (m2),A/V-Verhältnis Wohngebäude,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),GWP / m² NRF,Tiefgarage,Verkehrsfläche gesamt m²,Person_GWP,Person_GWP (GWP ohne Strom),Person_GWP (KG 300),Person_GWP (310 Erdaushub Keller),Person_GWP (322 Bodenplatte),Person_GWP (325 Bodenbelag),Person_GWP (331 Außenwand),Person_GWP (334 Außentüren),Person_GWP (339 Kellerwände),Person_GWP (334 Fenster),Person_GWP (341 Innenwände tragend (inkl. Aufzugschacht)),Person_GWP (342 Innenwände),Person_GWP (344 Innentüren),Person_GWP (351 Decken),Person_GWP (351 Treppe),Person_GWP (361 Dach),Person_GWP (KG 400),"Person_GWP (410 Abwasser, Trinkwasser)",Person_GWP (420 Wärmeversorgung),Person_GWP (430 Lüftung),Person_GWP (440 Strom),Person_GWP (460 Aufzug),Person_GWP (KG 500),Person_GWP (500 Quartiersstrom),Person_GWP (500 Quartierswasserleitung),Person_GWP (510 Erdaushub Leitungen),Person_GWP (510 Erdaushub Garagen),Person_GWP (521 Gehweg Radweg),Person_GWP (522 Straße),Person_GWP (524 Stellplätze),Person_GWP (524 Hochgaragen),Person_GWP (524 Tiefgaragen),Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (B6),Person_GWP (GWP für Nutzstrom)
498,ZM30NMSC,ZM30NMSC,ZH,Massiv,30 kWh,Nahwärme kalt,mittel,Kurve,Schlaufe,800498,800497.734249,291533.042761,2455.078597,26328.24,34764.808062,45678.672837,4716.406154,13018.45,23584.793143,36104.2656,17398.611692,889.521231,58968.155446,1039.68,26586.36,224245.9,246.24,192641.537354,19427.14368,8662.200103,3268.8,113472.0,291.592,912.0,28.448,6017.611126,4881.38,5626.32,3427.2,0.0,92287.827692,171246.0,171246.391532,0.0,511.0,Zeile,Schlaufe,60000.0,4728.0,4102.0,2720.0,12906.0,15884.307692,12707.446154,0.2151,0.8604,4.0,51624.0,57977.723077,41299.2,49281.064615,0.348417,16.0,41.0,1007.297561,529.476923,16.243515,True,11550.0,794.7,794.7,289.42,2.44,26.14,34.51,45.35,4.68,12.92,23.41,35.84,17.27,0.88,58.54,1.03,26.39,222.62,0.24,191.25,19.29,8.6,3.25,112.65,0.29,0.91,0.03,5.97,4.85,5.59,3.4,0.0,91.62,170.01,170.01,0.0

In [77]:
metrics_S3_ZH_50_1 = df_S3_ZH[[
    "GWP für Nutzstrom",
    "Anzahl Gebäude/ Kachel",
    "Nettowohnfläche pro Person (8) (statistisch)",
    "Nettoraumfläche NRF (m2)",
    "Bewohner Kachel insg. (rechnerisch)",
    "WE Kachel insg. (rechnerisch)",
    "Verkehrsfläche gesamt m²"
]].round(2)

metrics_S3_ZH_50_1

,GWP für Nutzstrom,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²
498,0.0,16.0,41.0,49281.06,1007.3,529.48,11550.0

In [78]:
# Dynamic scenario: Decarbonisation / 50 years

kg300 = 186420.393768
kg400 = 156378.659592
kg500 = 113472
b6 = 28435.17162

GWP = kg300 + kg400 + kg500 + b6

nrft = 49281.06  
people = 1007.3 
gwp_per_m2 = 9.833

metrics_S3_ZH_50_2 = {
    "GWP": GWP,
    "GWP für Bauwerk (KG 300)": kg300,
    "GWP für Haustechnik (KG 400)": kg400,
    "GWP für gesamte Geb.- Erschliessung (KG 500)": kg500,
    "GWP für Wärmeversorgung (B6)": b6,
    "GWP / m² NRF": gwp_per_m2,
    "GWP / m² NRF (rechnerisch)": GWP / nrft,
    "Person_GWP": GWP / people
}


metrics_df_2 = pd.DataFrame([metrics_S3_ZH_50_2])

metrics_df_2

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP / m² NRF,GWP / m² NRF (rechnerisch),Person_GWP
0,484706.22498,186420.393768,156378.659592,113472,28435.17162,9.833,9.835548,481.193512

In [79]:
S3_combined_metrics = metrics_S3_ZH_50_1.assign(**metrics_S3_ZH_50_2).round(2)

In [80]:
"""
------------------------------------------------------------------------------
S3: Overview metrics
------------------------------------------------------------------------------
"""
print("Line House:\n")
metrics_S3_ZH

Line House:

,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP für Nutzstrom,GWP / m² NRF,Person_GWP,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,Person_GWP (Summe Betrieb & Nutzstrom),Person_GWP (GWP für Nutzstrom)
498,800498,291533.04,224245.9,113472.0,171246.39,0.0,16.24,794.7,16.0,41.0,49281.06,1007.3,529.48,11550.0,170.01,0.0

In [81]:
print("Line House, Decarbonisation / 50 years:\n")
S3_combined_metrics

Line House, Decarbonisation / 50 years:

,GWP für Nutzstrom,Anzahl Gebäude/ Kachel,Nettowohnfläche pro Person (8) (statistisch),Nettoraumfläche NRF (m2),Bewohner Kachel insg. (rechnerisch),WE Kachel insg. (rechnerisch),Verkehrsfläche gesamt m²,GWP,GWP für Bauwerk (KG 300),GWP für Haustechnik (KG 400),GWP für gesamte Geb.- Erschliessung (KG 500),GWP für Wärmeversorgung (B6),GWP / m² NRF,GWP / m² NRF (rechnerisch),Person_GWP
498,0.0,16.0,41.0,49281.06,1007.3,529.48,11550.0,484706.22,186420.39,156378.66,113472,28435.17,9.83,9.84,481.19